const Images={
    northAmerica:{
    // australia:require('./../1x1/ac.svg').default,
    // india:require('./../1x1/in.svg').default,
    canada:[require('./../4x3/ca.svg').default,'Canada'],
    mexico:[require('./../4x3/mx.svg').default,'Mexico'],
    unitedStates:[require('./../4x3/us.svg').default,'United States'],
    },
    centralAmerica:{
        anguilla:[require('./../4x3/ai.svg',).default,'Anguilla'],
        antiguaAndBarbuda:[require('./../4x3/ag.svg').default,'Antigua & Barbuda'],
        aruba:[require('./../4x3/aw.svg').default,'Aruba'],
        bahamas:[require('./../4x3/bs.svg').default,'Bahamas'],
        barbados:[require('./../4x3/bb.svg').default,'Barbados'],
        belize:[require('./../4x3/bz.svg').default,'Belize'],
        bermuda:[require('./../4x3/bm.svg').default,'Bermuda'],
        britishVerginIslands:[require('./../4x3/vg.svg').default,'British Virgin Islands'],
        caribbeanNetherlands:[require('./../4x3/xx.svg').default,'Caribbean Netherlands'],
        caymanIslands:[require('./../4x3/ky.svg').default,'Cayman Islands'],
        costaRica:[require('./../4x3/cr.svg').default,'Costa Rica'],
        curaCao:[require('./../4x3/cw.svg').default,'Curacao'],
        dominica:[require('./../4x3/dm.svg').default,'Dominica'],
        dominicanRepublic:[require('./../4x3/do.svg').default,'Dominican Republic'],
        ElSalvador:[require('./../4x3/sv.svg').default,'El Salvador'],
        greenland:[require('./../4x3/gl.svg').default,'Greenland'],
        grenada:[require('./../4x3/gd.svg').default,'Grenada'],
        guadeloupe:[require('./../4x3/gp.svg').default,'Guadeloupe'],
        guatemala:[require('./../4x3/gt.svg').default,'Guatemala'],
        haiti:[require('./../4x3/ht.svg').default,'Haiti'],
        honduras:[require('./../4x3/hn.svg').default,'Honduras'],
        jamaica:[require('./../4x3/jm.svg').default,'Jamaica'],
        martinique:[require('./../4x3/mq.svg').default,'Martinique'],
        montserrat:[require('./../4x3/ms.svg').default,'Montserrat'],
        nicaragua:[require('./../4x3/ni.svg').default,'Nicaragua'],
        panama:[require('./../4x3/pa.svg').default,'Panama'],
        puertoRico:[require('./../4x3/pr.svg').default,'Puerto Rico'],
        sintMaarten:[require('./../4x3/sx.svg').default,'Sint Maarten'],
        stBarthelemy:[require('./../4x3/bl.svg').default,'St Barthélemy'],
        stKittsAndNevis:[require('./../4x3/kn.svg').default,'St Kitts & Nevis'],
        stLucia:[require('./../4x3/lc.svg').default,'St Lucia'],
        stMartin:[require('./../4x3/mf.svg').default,'St Martin'],
        stPierreAndMiquelon:[require('./../4x3/pm.svg').default,'St Pierre & Miquelon'],
        stVincentAndGrenadines:[require('./../4x3/vc.svg').default,'St Vincent & Grenadines'],
        trinidadAndTobago:[require('./../4x3/tt.svg').default,'Trinidad & Tobago'],
        turksAndCaicosIslands:[require('./../4x3/tc.svg').default,'Turks & Caicos Islands'],
    },
    southAmerica:{
        argentina:[require('./../4x3/ar.svg').default,'Argentina'],
        bolivia:[require('./../4x3/bo.svg').default,'Bolivia'],
        bouvetIsland:[require('./../4x3/bv.svg').default,'Bouvet Island'],
        brazil:[require('./../4x3/br.svg').default,'Brazil'],
        chile:[require('./../4x3/cl.svg').default,'Chile'],
        colombia:[require('./../4x3/co.svg').default,'Colombia'],
        ecuador:[require('./../4x3/ec.svg').default,'Ecuador'],
        falklandIslands:[require('./../4x3/fk.svg').default,'Falkland Islands'],
        frenchGuiana:[require('./../4x3/gf.svg').default,'French Guoana'],
        guyana:[require('./../4x3/gy.svg').default,'Guyana'],
        paraguay:[require('./../4x3/py.svg').default,'Paraguay'],
        peru:[require('./../4x3/pe.svg').default,'Peru'],
        southGeorgiaAndSouthSandwichIslands:[require('./../4x3/gs.svg').default,'South Georgia & South Sandwich Island'],
        suriname:[require('./../4x3/sr.svg').default,'Suriname'],
        uruguay:[require('./../4x3/uy.svg').default,'Uruguay'],
        venezuela:[require('./../4x3/ve.svg').default,'Venezuela'],
    },
    europe:{
        alandIslands:[require('./../4x3/ax.svg').default,'Åland Islands'],
        albania:[require('./../4x3/al.svg').default,'Albania'],
        andorra:[require('./../4x3/ad.svg').default,'Andorra'],
        austria:[require('./../4x3/at.svg').default,'Austria'],
        belarus:[require('./../4x3/by.svg').default,'Belarus'],
        belgium:[require('./../4x3/be.svg').default,'Belgium'],
        bosniaAndHerzegovina:[require('./../4x3/ba.svg').default,'Bosnia & Herzegoviana'],
        bulgaria:[require('./../4x3/bg.svg').default,'Bulgaria'],
        croatia:[require('./../4x3/hr.svg').default,'Croatia'],
        czechRepblic:[require('./../4x3/cz.svg').default,'Czech Republic'],
        denmark:[require('./../4x3/dk.svg').default,'Denmark'],
        estonia:[require('./../4x3/ee.svg').default,'Estonia'],
        faroeIslands:[require('./../4x3/fo.svg').default,'Faroe Islands'],
        finland:[require('./../4x3/fi.svg').default,'Finland'],
        france:[require('./../4x3/fr.svg').default,'France'],
        germany:[require('./../4x3/de.svg').default,'Germany'],
        gibraltar:[require('./../4x3/gi.svg').default,'Gibraltar'],
        greece:[require('./../4x3/gr.svg').default,'Greece'],
        guernsey:[require('./../4x3/gg.svg').default,'Guernsey'],
        hungary:[require('./../4x3/hu.svg').default,'Hungary'],
        iceland:[require('./../4x3/is.svg').default,'Iceland'],
        ireland:[require('./../4x3/ie.svg').default,'Ireland'],
        isleOfMan:[require('./../4x3/im.svg').default,'Isle of Man'],
        italy:[require('./../4x3/it.svg').default,'Italy'],
        jersey:[require('./../4x3/je.svg').default,'Jersey'],
        kosovo:[require('./../4x3/xk.svg').default,'Kosovo'],
        latvia:[require('./../4x3/lv.svg').default,'Latvia'],
        liechtenstein:[require('./../4x3/li.svg').default,'Liechtenstein'],
        lithuania:[require('./../4x3/lt.svg').default,'Lithuania'],
        luxembourg:[require('./../4x3/lu.svg').default,'Luxembourg'],
        malta:[require('./../4x3/mt.svg').default,'Malta'],
        moldova:[require('./../4x3/md.svg').default,'Moldova'],
        monaco:[require('./../4x3/mc.svg').default,'Monaco'],
        montenegro:[require('./../4x3/me.svg').default,'Montenegro'],
        netherlands:[require('./../4x3/nl.svg').default,'Netherlands'],
        northMacedonia:[require('./../4x3/mk.svg').default,'North Macedonia'],
        norway:[require('./../4x3/no.svg').default,'Norway'],
        poland:[require('./../4x3/pl.svg').default,'poland'],
        portugal:[require('./../4x3/pt.svg').default,'Portugal'],
        romania:[require('./../4x3/ro.svg').default,'Romania'],
        russia:[require('./../4x3/ru.svg').default,'Russia'],
        sanMarino:[require('./../4x3/sm.svg').default,'San Marino'],
        serbia:[require('./../4x3/rs.svg').default,'Serbia'],
        slovakia:[require('./../4x3/sk.svg').default,'Slovakia'],
        slovenia:[require('./../4x3/si.svg').default,'Slovenia'],
        spain:[require('./../4x3/es.svg').default,'Spain'],
        svalbardAndJanMayen:[require('./../4x3/sj.svg').default,'Svalbard & Jan Mayen'],
        sweden:[require('./../4x3/se.svg').default,'Sweden'],
        switzerland:[require('./../4x3/ch.svg').default,'Switzerland'],
        ukraine:[require('./../4x3/ua.svg').default,'Ukraine'],
        unitedKingdom:[require('./../4x3/gb.svg').default,'United Kingdom'],
        vaticanCity:[require('./../4x3/va.svg').default,'Vatican City'],
    },
    Africa:{
        algeria:[require('./../4x3/dz.svg').default,'Algeria'],
        angola:[require('./../4x3/ao.svg').default,'Angola'],
        benin:[require('./../4x3/bj.svg').default,'Benin'],
        botswana:[require('./../4x3/bw.svg').default,'Botswana'],
        britishIndianOceanTerritory:[require('./../4x3/io.svg').default,'British Indian Ocean Territory'],
        burkinaFaso:[require('./../4x3/bf.svg').default,'Burkina Faso'],
        burundi:[require('./../4x3/bi.svg').default,'Burundi'],
        cameroon:[require('./../4x3/cm.svg').default,'Cameroon'],
        capeVerde:[require('./../4x3/cv.svg').default,'Cape Verde'],
        centralAfricanRepublic:[require('./../4x3/cf.svg').default,'Central American Republic'],
        chad:[require('./../4x3/td.svg').default,'Chad'],
        comoros:[require('./../4x3/km.svg').default,'Comoros'],
        congoBrazzaville:[require('./../4x3/cg.svg').default,'Congo-Brazzaville'],
        congokinshasa:[require('./../4x3/cd.svg').default,'congo-Kinshasa'],
        coteDIvoire:[require('./../4x3/ci.svg').default,'Côte d’Ivoire'],
        djibouti:[require('./../4x3/dj.svg').default,'Djibouti'],
        egypt:[require('./../4x3/eg.svg').default,'Egypt'],
        equatorialGuinea:[require('./../4x3/gq.svg').default,'Equatorial Guinea'],
        eritrea:[require('./../4x3/er.svg').default,'Eritrea'],
        eswatini:[require('./../4x3/sz.svg').default,'Eswatini'],
        ethiopia:[require('./../4x3/et.svg').default,'Ethiopia'],
        frenchSouthernTerritories:[require('./../4x3/tf.svg').default,'French Southern Territories'],
        gabon:[require('./../4x3/ga.svg').default,'Gabon'],
        gambia:[require('./../4x3/gm.svg').default,'Gambia'],
        ghana:[require('./../4x3/gh.svg').default,'Ghana'],
        guinea:[require('./../4x3/gn.svg').default,'Guinea'],
        guineaBissau:[require('./../4x3/gw.svg').default,'Guinea-Bissau'],
        kenya:[require('./../4x3/ke.svg').default,'Kenya'],
        lesotho:[require('./../4x3/ls.svg').default,'Lesotho'],
        liberia:[require('./../4x3/lr.svg').default,'Liberia'],
        libya:[require('./../4x3/ly.svg').default,'Libya'],
        madagascar:[require('./../4x3/mg.svg').default,'Madagascar'],
        malawi:[require('./../4x3/mw.svg').default,'Malawi'],
        mali:[require('./../4x3/ml.svg').default,'Mali'],
        mauritania:[require('./../4x3/mr.svg').default,'Mauritania'],
        mauritius:[require('./../4x3/mu.svg').default,'Mauritius'],
        mayotte:[require('./../4x3/yt.svg').default,'Mayotte'],
        morocco:[require('./../4x3/ma.svg').default,'Morocco'],
        mozambique:[require('./../4x3/mz.svg').default,'Mozambique'],
        namibia:[require('./../4x3/na.svg').default,'Namibia'],
        niger:[require('./../4x3/ne.svg').default,'Niger'],
        nigeria:[require('./../4x3/ng.svg').default,'Nigeria'],
        reunion:[require('./../4x3/re.svg').default,'Réunion'],
        rwanda:[require('./../4x3/rw.svg').default,'Rwanda'],
        saoTomeAndPrincipe:[require('./../4x3/st.svg').default,'São Tomé & Príncipe'],
        senegal:[require('./../4x3/sn.svg').default,'Senegal'],
        seychelles:[require('./../4x3/sc.svg').default,'Seychelles'],
        seirraLeone:[require('./../4x3/sl.svg').default,'Sierra Leone'],
        somalia:[require('./../4x3/so.svg').default,'Somalia'],
        southAfrica:[require('./../4x3/za.svg').default,'South Africa'],
        southSudan:[require('./../4x3/ss.svg').default,'South Sudan'],
        stHelana:[require('./../4x3/sh.svg').default,'St Helena'],
        tanzania:[require('./../4x3/tz.svg').default,'Tanzania'],
        togo:[require('./../4x3/tg.svg').default,'Togo'],
        tristanDaCunha:[require('./../4x3/ta.svg').default,'Tristan da Cunha'],
        tunisia:[require('./../4x3/tn.svg').default,'Tunisia'],
        uganda:[require('./../4x3/ug.svg').default,'Uganda'],
        zambia:[require('./../4x3/zm.svg').default,'Zambia'],
        zimbabwe:[require('./../4x3/zw.svg').default,'Zimbabwe'],
    },
    Asia:{
        afghanistan:[require('./../4x3/af.svg').default,'afghanistan'],
        armenia:[require('./../4x3/am.svg').default,'Armenia'],
        azerbaijan:[require('./../4x3/az.svg').default,'Azerbaijan'],
        bahrain:[require('./../4x3/bh.svg').default,'Bahrain'],
        bangladesh:[require('./../4x3/bd.svg').default,'Bangladesh'],
        bhutan:[require('./../4x3/bt.svg').default,'Bhutan'],
        brunei:[require('./../4x3/bn.svg').default,'Brunei'],
        cambodia:[require('./../4x3/kh.svg').default,'Cambodia'],
        china:[require('./../4x3/cn.svg').default,'China'],
        cyprus:[require('./../4x3/cy.svg').default,'Cyprus'],
        georgia:[require('./../4x3/ge.svg').default,'Georgia'],
        hongKongsarChina:[require('./../4x3/hk.svg').default,'Hong Kong SAR China'],
        india:[require('./../4x3/in.svg').default,'India'],
        indonesia:[require('./../4x3/id.svg').default,'Indonesia'],
        iraq:[require('./../4x3/iq.svg').default,'Iraq'],
        israel:[require('./../4x3/il.svg').default,'Israel'],
        japan:[require('./../4x3/jp.svg').default,'Japan'],
        jordan:[require('./../4x3/jo.svg').default,'Jordan'],
        kazakhstan:[require('./../4x3/kz.svg').default,'Kazakhstan'],
        kuwait:[require('./../4x3/kw.svg').default,'Kuwait'],
        kyrgyzstan:[require('./../4x3/kg.svg').default,'Kyrgyzstan'],
        laos:[require('./../4x3/la.svg').default,'Laos'],
        lebanon:[require('./../4x3/lb.svg').default,'Lebanon'],
        macaoSarChina:[require('./../4x3/mo.svg').default,'Macao SAR China'],
        malaysia:[require('./../4x3/my.svg').default,'Malaysia'],
        maldives:[require('./../4x3/mv.svg').default,'Maldives'],
        mongolia:[require('./../4x3/mn.svg').default,'Mongolia'],
        myanmarOrBurma:[require('./../4x3/mm.svg').default,'Myanmar (Burma)'],
        nepal:[require('./../4x3/np.svg').default,'Nepal'],
        oman:[require('./../4x3/om.svg').default,'Oman'],
        pakistan:[require('./../4x3/pk.svg').default,'Pakistan'],
        philippines:[require('./../4x3/ph.svg').default,'Philippines'],
        qatar:[require('./../4x3/qa.svg').default,'Qatar'],
        saudiArabia:[require('./../4x3/sa.svg').default,'Saudi Arabia'],
        singapore:[require('./../4x3/sg.svg').default,'Singapore'],
        southKorea:[require('./../4x3/kr.svg').default,'South Korea'],
        sriLanka:[require('./../4x3/lk.svg').default,'Sri Lanka'],
        taiwan:[require('./../4x3/tw.svg').default,'Taiwan'],
        tajikistan:[require('./../4x3/tj.svg').default,'Tajikistan'],
        thailand:[require('./../4x3/th.svg').default,'Thailand'],
        timorleste:[require('./../4x3/tl.svg').default,'Timor-Leste'],
        turkey:[require('./../4x3/tr.svg').default,'Turkey'],
        turkmenistan:[require('./../4x3/tm.svg').default,'Turkmenistan'],
        unitedArabEmirates:[require('./../4x3/ae.svg').default,'United Arab Emirates'],
        uzbekistan:[require('./../4x3/uz.svg').default,'Uzbekistan'],
        vietnam:[require('./../4x3/vn.svg').default,'Vietnam'],
        yemen:[require('./../4x3/ye.svg').default,'Yemen'],
    },
    oceania:{
        australia:[require('./../4x3/au.svg').default,'Australia'],
        cookIslands:[require('./../4x3/ck.svg').default,'Cook Islands'],
        fiji:[require('./../4x3/fj.svg').default,'Fiji'],
        frenchPolynesia:[require('./../4x3/pf.svg').default,'French Polynesia'],
        guam:[require('./../4x3/gu.svg').default,'Guam'],
        kiribati:[require('./../4x3/ki.svg').default,'Kiribati'],
        nauru:[require('./../4x3/nr.svg').default,'Nauru'],
        newCaledonia:[require('./../4x3/nc.svg').default,'New Caledonia'],
        newZealand:[require('./../4x3/nz.svg').default,'New Zealand'],
        niue:[require('./../4x3/nu.svg').default,'Niue'],
        papuaNewGuinea:[require('./../4x3/pg.svg').default,'Papua New Guinea'],
        pitcairnIslands:[require('./../4x3/pn.svg').default,'Pitcairn Islands'],
        samoa:[require('./../4x3/ws.svg').default,'Samoa'],
        solomonIslands:[require('./../4x3/sb.svg').default,'Solomon Islands'],
        tokelau:[require('./../4x3/tk.svg').default,'Tokelau'],
        tonga:[require('./../4x3/to.svg').default,'Tonga'],
        tuvalu:[require('./../4x3/tv.svg').default,'Tuvalu'],
        vanuatu:[require('./../4x3/vu.svg').default,'Vanuatu'],
        wallisAndFutuna:[require('./../4x3/wf.svg').default,'Wallis & Futuna'],
    }
}
export default Images;